----DROP DATABASE POKEDEXDB

----CREATE DATABASE POKEDEXDB

----DROP TABLE Pokemon

--CREATE TABLE USERNAME
--(
--	USERNAMEID INT NOT NULL IDENTITY(1,1) PRIMARY KEY
--	,USERNAME VARCHAR (5)
--)

--CREATE TABLE HIGHSCORE
--(
--	HIGHSCOREID INT NOT NULL IDENTITY(1,1) PRIMARY KEY
--	,HIGHSCORE INT
--	,USERNAMEID INT
--	,FOREIGN KEY (USERNAMEID) REFERENCES USERNAME (USERNAMEID)
--);
